services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://myodex:myodex@db:5432/myodex
    depends_on:
      db:
        condition: service_healthy
      

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myodex
      POSTGRES_PASSWORD: myodex
      POSTGRES_DB: myodex
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myodex"]
      interval: 2s
      timeout: 5s
      retries: 10
      

volumes:
  postgres_data: