"""initial schema

Revision ID: d96c92030abb
Revises: 
Create Date: 2026-10-10 00:08:06.709502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd96c92030abb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal_presets',
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('sets', sa.String(length=10), nullable=False),
    sa.Column('reps', sa.String(length=20), nullable=False),
    sa.Column('rest', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('muscles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_muscles_slug'), 'muscles', ['slug'], unique=True)
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('target', sa.String(length=50), nullable=False),
    sa.Column('secondary', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.ForeignKeyConstraint(['target'], ['muscles.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_category'), 'exercises', ['category'], unique=False)
    op.create_index(op.f('ix_exercises_target'), 'exercises', ['target'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercises_target'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_category'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_muscles_slug'), table_name='muscles')
    op.drop_table('muscles')
    op.drop_table('goal_presets')
    # ### end Alembic commands ###
